export const GETCURRENTPRICE = "GETCURRENTPRICE";
export const FETCHEDCURRENTPRICE = "FETCHEDCURRENTPRICE";
export const GETPRICEDROP = "GETPRICEDROP";
export const FETCHEDPRICEDROP = "FETCHEDPRICEDROP";
